-- Create tables for RooVibe application

-- 1. profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  display_name text,
  avatar_url text,
  bio text,
  is_creator boolean DEFAULT false,
  telegram_handle text,
  whatsapp_handle text,
  city text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id );

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

-- Trigger to call handle_new_user on auth.users insert
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. posts table
CREATE TABLE IF NOT EXISTS public.posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  title text NOT NULL,
  story text,
  price numeric,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT posts_pkey PRIMARY KEY (id)
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Posts are viewable by everyone."
  ON public.posts FOR SELECT
  USING ( true );

CREATE POLICY "Creators can insert their own posts."
  ON public.posts FOR INSERT
  WITH CHECK ( auth.uid() = creator_id );

CREATE POLICY "Creators can update their own posts."
  ON public.posts FOR UPDATE
  USING ( auth.uid() = creator_id );

CREATE POLICY "Creators can delete their own posts."
  ON public.posts FOR DELETE
  USING ( auth.uid() = creator_id );

-- 3. tags table
CREATE TABLE IF NOT EXISTS public.tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  CONSTRAINT tags_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tags are viewable by everyone."
  ON public.tags FOR SELECT
  USING ( true );

CREATE POLICY "Authenticated users can insert tags."
  ON public.tags FOR INSERT
  WITH CHECK ( auth.role() = 'authenticated' );

-- 4. post_tags table
CREATE TABLE IF NOT EXISTS public.post_tags (
  post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  CONSTRAINT post_tags_pkey PRIMARY KEY (post_id, tag_id)
);

ALTER TABLE public.post_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Post tags are viewable by everyone."
  ON public.post_tags FOR SELECT
  USING ( true );

CREATE POLICY "Creators can insert post tags for their own posts."
  ON public.post_tags FOR INSERT
  WITH CHECK ( auth.uid() IN (SELECT creator_id FROM public.posts WHERE id = post_id) );

CREATE POLICY "Creators can delete post tags for their own posts."
  ON public.post_tags FOR DELETE
  USING ( auth.uid() IN (SELECT creator_id FROM public.posts WHERE id = post_id) );

-- 5. saves table
CREATE TABLE IF NOT EXISTS public.saves (
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT saves_pkey PRIMARY KEY (user_id, post_id)
);

ALTER TABLE public.saves ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own saves."
  ON public.saves FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can insert their own saves."
  ON public.saves FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own saves."
  ON public.saves FOR DELETE
  USING ( auth.uid() = user_id );

-- 6. follows table
CREATE TABLE IF NOT EXISTS public.follows (
  follower_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  creator_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT follows_pkey PRIMARY KEY (follower_id, creator_id)
);

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own follows."
  ON public.follows FOR SELECT
  USING ( auth.uid() = follower_id );

CREATE POLICY "Users can insert their own follows."
  ON public.follows FOR INSERT
  WITH CHECK ( auth.uid() = follower_id );

CREATE POLICY "Users can delete their own follows."
  ON public.follows FOR DELETE
  USING ( auth.uid() = follower_id );

-- Setup storage for posts
INSERT INTO storage.buckets (id, name, public) VALUES ('posts', 'posts', true) ON CONFLICT DO NOTHING;

CREATE POLICY "Post images are viewable by everyone."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'posts' );

CREATE POLICY "Creators can upload post images."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'posts' AND auth.role() = 'authenticated' );

CREATE POLICY "Creators can update their post images."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'posts' AND auth.role() = 'authenticated' );

CREATE POLICY "Creators can delete their post images."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'posts' AND auth.role() = 'authenticated' );
